service: immo-crm

image: ghcr.io/laurentqro/immo-crm

servers:
  web:
    - 167.235.54.90

proxy:
  ssl: true
  host: bos.curau.dev

registry:
  server: ghcr.io
  username: laurentqro
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
  clear:
    SOLID_QUEUE_IN_PUMA: true
    DB_HOST: 178.104.30.228

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

volumes:
  - "immo_crm_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch:
    - amd64
    - arm64
  remote: ssh://root@167.235.54.90

accessories:
  db:
    image: postgres:17
    host: 178.104.30.228
    port: 5432
    env:
      clear:
        POSTGRES_USER: immo_crm
        POSTGRES_DB: immo_crm_production
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
